/**
 * Express type extensions for the finance-flow backend
 */

declare global {
  namespace Express {
    interface Request {
      /**
       * Unique request ID for tracing and logging
       * Generated by the request ID middleware
       */
      id?: string;
    }
  }
}

export {};