/**
 * Application constants and configuration values
 * Centralizes magic numbers and reusable constants
 */

// Validation Constants
export const VALIDATION = {
  CATEGORY_NAME_MIN_LENGTH: 1,
  CATEGORY_NAME_MAX_LENGTH: 100,
} as const;

// File System Constants  
export const FILE_SYSTEM = {
  LOCK_STALE_TIMEOUT_MS: 30000,
  LOCK_RETRY_COUNT: 3,
  LOCK_MIN_TIMEOUT_MS: 100,
  LOCK_MAX_TIMEOUT_MS: 2000,
  LOCK_RETRY_FACTOR: 2,
} as const;

// Date and Time Constants
export const TIME = {
  DAYS_PER_MONTH: 30.44, // Average days per month for calculations
  MONTHS_PER_YEAR: 12,
  MS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  get MILLISECONDS_PER_MONTH() {
    return this.MS_PER_SECOND * this.SECONDS_PER_MINUTE * this.MINUTES_PER_HOUR * this.HOURS_PER_DAY * this.DAYS_PER_MONTH;
  },
} as const;

// Projection Constants
export const PROJECTIONS = {
  MIN_CALCULATION_PERIOD_MONTHS: 3,
  MAX_CALCULATION_PERIOD_MONTHS: 24,
  DEFAULT_CALCULATION_PERIOD_MONTHS: 12,
  MIN_PROJECTION_PERIOD_MONTHS: 3,
  MAX_PROJECTION_PERIOD_MONTHS: 60,
  DEFAULT_PROJECTION_PERIOD_MONTHS: 12,
  MAX_MONTHLY_GROWTH_RATE: 0.5,  // 50%
  MIN_MONTHLY_GROWTH_RATE: -0.5, // -50%
  MAX_FALLBACK_MONTHLY_RATE: 0.1,  // 10%
  MIN_FALLBACK_MONTHLY_RATE: -0.1, // -10%
  MIN_HISTORY_POINTS_FOR_PROJECTION: 2,
  MIN_HISTORY_POINTS_FOR_ADVANCED_CALCULATION: 6,
} as const;

// HTTP Status Codes (commonly used ones)
export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

// Error Codes
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FORMAT: 'INVALID_FORMAT',
  READ_ERROR: 'READ_ERROR',
  WRITE_ERROR: 'WRITE_ERROR',
  FILE_BUSY: 'FILE_BUSY',
  SECURITY_ERROR: 'SECURITY_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  DIRECTORY_ERROR: 'DIRECTORY_ERROR',
  NO_DATA: 'NO_DATA',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  DUPLICATE_CATEGORY: 'DUPLICATE_CATEGORY',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  OPERATION_FAILED: 'OPERATION_FAILED',
  INVALID_DATA_STRUCTURE: 'INVALID_DATA_STRUCTURE',
  INVALID_NODES_FORMAT: 'INVALID_NODES_FORMAT',
  INVALID_LINKS_FORMAT: 'INVALID_LINKS_FORMAT',
} as const;